arch: arm64
os: linux
dist: focal

branches:
  only:
    - main

language: go

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.127.0/hugo_0.127.0_linux-arm64.deb
  - sudo dpkg -i hugo*.deb

script:
  - HUGO_ENV=production hugo --gc --minify -v -b https://lnfu.github.io

deploy:
  on:
    branch: main
  strategy: git
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  target_branch: gh-pages

notifications:
  email:
      recipients:
        - enfu.liao.cs10@nycu.edu.tw
      on_success: always
      on_failure: always

