baseURL = 'https://efliao.com/'
languageCode = 'en-us'
title = 'Enfu Liao'


[params]
  since = '2024'
  [params.author]
    email = 'efliao@cs.nycu.edu.tw'
    name = 'Enfu Liao'

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 1

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 2
